The MVС pattern is implemented.
Htocki/Game pull request #4
Opened 2020-04-21 13:28 UTC by Htocki

2020-09-21 06:26 UTC, sialiuk requested changes

2020-09-21 06:26 UTC, sialiuk commented on game/lib/view/assets/include/Assets.h
> +  static Assets& Instance() {
It's better to return const reference because all public methods are const

2020-09-21 06:26 UTC, sialiuk commented on game/lib/utility/handable/src/EventHandlerKeeper.cpp
> +  for (const auto& event_handler : m_event_handlers) {
auto*

2020-09-21 06:26 UTC, sialiuk commented on game/lib/utility/handable/include/EventHandlerKeeper.h
> +class sf::Event;
move forward declaration out of namespace "Game" scope

2020-09-21 06:26 UTC, sialiuk commented on game/lib/utility/handable/include/EventHandler.h
> +class sf::Event;
move forward declaration out of namespace "Game" scope

2020-09-21 06:26 UTC, sialiuk commented on game/lib/model/positionable/include/Positionable.h
> +  Position GetPosition() const;
Remove getter and setter, or make m_position private

2020-09-21 06:26 UTC, sialiuk commented on game/lib/model/application/include/Application.h
> +class Application : public EventHandlerKeeper {
Should be private inheritance

2020-09-21 09:33 UTC, Htocki commented on game/lib/view/assets/include/Assets.h
> +  static Assets& Instance() {
Ok.

2020-09-21 09:33 UTC, Htocki commented on game/lib/utility/handable/src/EventHandlerKeeper.cpp
> +  for (const auto& event_handler : m_event_handlers) {
Ok.

2020-09-21 09:37 UTC, Htocki commented on game/lib/utility/handable/include/EventHandlerKeeper.h
> +class sf::Event;
Ok.

2020-09-21 09:38 UTC, Htocki commented on game/lib/utility/handable/include/EventHandler.h
> +class sf::Event;
Ok.

2020-09-21 09:40 UTC, Htocki commented on game/lib/model/positionable/include/Positionable.h
> +  Position GetPosition() const;
Ok.

2020-09-21 15:54 UTC, Htocki commented on game/lib/model/application/include/Application.h
> +class Application : public EventHandlerKeeper {
Ok.

2020-09-24 14:36 UTC, sialiuk approved these changes

2020-09-24 14:37 UTC, merged